import type { Metadata } from 'next';
import { Lexend_Deca } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

export const glysa = localFont({
  src: './glysa-webfont.woff2',
  display: 'swap',
});

const lexendDeca = Lexend_Deca({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.className} antialiased`}>{children}</body>
    </html>
  );
}
